services:
  redis-server:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  node-app:
    build: .
    ports:
      - '8080:8080'

volumes:
  redis-data:
